export enum ExtensionAction {
  UPDATE_OPTIONS = 'updateOptions',
  OPEN_SIGN_IN_PAGE = 'openSignInPage',
  GET_SELECTORS = 'getSelectors',
  ON_SITE_UPDATE = 'onSiteUpdate',
  TEST_MESSAGE = 'testMessage',
  GET_POPUP_DATA = 'getPopupData',
  GET_OPTIONS_DATA = 'getOptionsData',
  OPEN_NOTIFS_PAGE = 'openNotifsPage',
  OPEN_MESSAGES_PAGE = 'openMessagesPage',
  OPEN_WATCH_PAGE = 'openWatchPage',
  INSTANT_UPDATE = 'instantUpdate',
  SET_MARK_READ = 'setMarkRead',
  CLEAR_MARK_READ = 'clearMarkRead',
  BROADCAST_POPUP_UPDATE = 'broadcastPopupUpdate',
}
